### ISSUE TITLE
FPV Shopping list

### ISSUE THREAD

**Issue by juliusakula** [murdockfpv/murdockfpv.github.io#21]
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B07VRP1V76&asins=B07VRP1V76&linkId=31dc48948db0bdc72a5f43178fcc9450&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B07RGF3CFH&asins=B07RGF3CFH&linkId=cebc0bf66379dab961c3386ff496aecb&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

**Comment by juliusakula** [comment]
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B07WQQ5KQ6&asins=B07WQQ5KQ6&linkId=3d54faceba12fe3c8dbfaa3dc9278635&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B08LMWTBJ9&asins=B08LMWTBJ9&linkId=244f65767a12fb94480c419cec08cf7a&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B08MT3RGWR&asins=B08MT3RGWR&linkId=1618f261ce8735a4ba4da0a118fd06df&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

**Comment by juliusakula** [comment]
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B083QC5V7X&asins=B083QC5V7X&linkId=62835af7b5e317a600365a7670277597&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B083F815JV&asins=B083F815JV&linkId=45a4522ca246b3d7c7c35bd8e5bcf680&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B0711H4D3K&asins=B0711H4D3K&linkId=da34ce4891e9e6956c4b3325d39d4a66&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

**Comment by juliusakula** [comment]
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B076BWMTL7&asins=B076BWMTL7&linkId=d62d2219529d06f7bbf63f4afa8dc9b1&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

**Comment by juliusakula** [comment]
### Audio

An accessory I need more than anything right now is a [Lavalier Microphone](https://www.amazon.com/dp/B0856V2C5Q/ref=as_sl_pc_tf_til?tag=juliusakula-20&linkCode=w00&linkId=57438679284ee330005ef349588dd5fc&creativeASIN=B0856V2C5Q "Lavalier Microphone on Amazon") for better audio when I take videos. A few months ago I ordered a lav mic - the Movo brand, and it was so terrible I returned it after one use. With two microphones, you would expect Person 1 to be on Channel 1, and Person 2 to be on Channel 2. With the Movo, Person 1 and 2 were on Channel 1, so there was no way to isolate the sound. Imagine doing an interview, but when one person is talking you can hear the other person breathing or drinking water. This Comica has good reviews and I was really impressed with the sound quality and the range. I'll be buying this and have about $300 leftover.

This will allow me to set my phone up on a tripod, mic myself up, connect my tablet to my drone, and fly while doing commentary/voiceover.
  
#### Comica Lavalier Microphone system:

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ac&ref=tf_til&ad_type=product_link&tracking_id=juliusakula-20&marketplace=amazon&region=US&placement=B0856V2C5Q&asins=B0856V2C5Q&linkId=57438679284ee330005ef349588dd5fc&show_border=true&link_opens_in_new_window=false&price_color=333333&title_color=0066c0&bg_color=ffffff">
    </iframe>

**Comment by juliusakula** [comment]
#### Additional Research on goggles 

[![Fat Shark HDO](http://img.youtube.com/vi/f8HXBizoLK8/0.jpg)](http://www.youtube.com/watch?v=f8HXBizoLK8 "Fat Shark HDO")

##### [Fat Shark HDO (goes to youtube)](http://www.youtube.com/watch?v=f8HXBizoLK8)

With the Eachine EV800D I can have a functioning pair of FPV goggles, which will be great for starting, especially at a price point of $130. I will be limited on my range and really won't be able to fly that well according to some of these FPV racers. I imagine flying well to be defined as 

[![Eachine EV800D](http://img.youtube.com/vi/1sfR8ny2BQ0/0.jpg)](http://www.youtube.com/watch?v=1sfR8ny2BQ0 "Eachine EV800D")

##### [Eachine EV800D (goes to youtube)](http://www.youtube.com/watch?v=1sfR8ny2BQ0)

#### Goggles on the tightest budget

$60 goggles versus $650 goggles (EACHINE entry level -- I couldn't find availability of the ones in this review, but watched reviews for Eachine EV800DM as well and the consensus was "good enough" and especially just good for someone starting out)- https://www.youtube.com/watch?v=f8HXBizoLK8

Rotor Riot review 3 different BUDGET fat shark goggles [From a person who prefers box goggles instead of the VR dual-screen goggles] https://www.youtube.com/watch?v=EfCAqYMHtXo

Some Budget goggles with great reviews for $79 - Hawkeye. Uses mirrors to increase focal distance and reduce eye strain. Amazing review. https://www.youtube.com/watch?v=u0SG3hAZkrM

**Comment by mallbritten** [comment]
Change Electronics Shopping Boogaloo to something else.

**Comment by mallbritten** [comment]
Add affiliate links other than Amazon.

**Comment by mallbritten** [comment]
Consider splitting up paragraphs so they don't look so daunting. Blocks of text can deter people from reading.

**Comment by juliusakula** [comment]
add images

**Comment by juliusakula** [comment]
add images of both controllers taranis Q X7 and X9D

**Comment by juliusakula** [comment]
the "at any rate" bullet point

**Comment by mallbritten** [comment]
instead of "I hope you like drones as much as I do." maybe say something more personal, like "I hope you'll come back to my page for future drone references!"

**Comment by juliusakula** [comment]
REMOVED --

Now, on the subject of drones crashing, [Nurk FPV has a video (27:00+)](https://www.youtube.com/watch?v=RKVx8-43eZg) in which he shows that he packs _**6**_ drones for a flight/video shoot. That may seem excessive but if you watch FPV videos this is not unreasonable considering how often he crashes, and the video is eye opening to the experience of being a highly skilled pilot who travels to do video work for clients. I recommend watching a lot of videos if you are interested in FPV.

**Comment by juliusakula** [comment]
ADD TO END ---

All the product links on this page go to amazon. I am affiliated with 11 companies -- Amazon, DJI, GetFPV, HobbyKing, BangGood, DealExtreme, DHGATE, TOMTOP, EmaxUSA, MakerFire, and FlexRC and have created a seperate page with LOADS of links to products you could purchase as you enter the FPV world, and all those links could earn me a comission. \[LINK\]\(\)

**Comment by juliusakula** [comment]
https://emax-usa.com/products/tinyhawk-rtf-kit-including-googles-and-radio?ref=7P96ayzbPSlSj

**Comment by juliusakula** [comment]
Cheapest

https://emax-usa.com/products/tinyhawk-rtf-kit-including-googles-and-radio?ref=7P96ayzbPSlSj

$165 includes everything

**Comment by juliusakula** [comment]
<ul>
  <li>DRONE SIMULATOR!! <a href="https://www.youtube.com/watch?v=J6NSeg-rD0c&amp;list=PL8PM0sBqDJTHhTA9U-Q8c13RHr7gX3S54&amp;index=1&amp;t=7s">Nurk FPV “The First things you should buy when getting into FPV”</a>. - About two minutes into the video he talks about buying a controller first, and playing the drone simulator before even buying a drone. Playing the drone simulator can make you a good drone pilot before you ever fly a real drone. Find the Drone Racing Simulator game on Steam.</li>
  <li>YOUR FIRST DRONE BUILD! <a href="https://www.youtube.com/watch?v=FEittnx42Zc&amp;list=PL8PM0sBqDJTHhTA9U-Q8c13RHr7gX3S54&amp;index=4">Joshua Bardwell - “FPV Drone Budget Build Full Tutorial - Part 1 - Assembly”
</a>. - This video’s description contains SO MANY links… soldering tutorials and has links to soldering irons to buy and also every drone component in the video, you can buy and follow along to the video and viola you now know how to build drones. I think this is an excellent getting started series. Not very thrilling, but informative and educational.</li>
  <li>Building a Drone with $99 to spend <a href="https://www.youtube.com/watch?v=GFNGUDT_9_c&amp;list=PL8PM0sBqDJTHhTA9U-Q8c13RHr7gX3S54&amp;index=5&amp;t=381s">UAVFutures - “Build a PRO FPV Racing Drone for ONLY $99 Full guide - 2018 UAVFUTURES $99 Build”</a></li>
  <li>Building a drone with $200 to spend <a href="https://www.youtube.com/watch?v=ZyQOkRjt_h0&amp;list=PL8PM0sBqDJTHhTA9U-Q8c13RHr7gX3S54&amp;index=3">$200 FPV Drone Build &amp; Set Up! - The Rotor Riot Budget Build</a></li>
</ul>

**Comment by juliusakula** [comment]
REMOVED 


For the controller I chose the Taranis X9D over the Q X7 because while the Q X7 is $100 cheaper, it doesn't have the feature of simply being able to plug in the controller and charge it. The Q X7 you must buy a battery seperately and charge it which seems like a big pain. The X9D is a good controller that you could use for the [Drone Racing League Simulator game on Steam](https://store.steampowered.com/app/641780/The_Drone_Racing_League_Simulator/) game, or for any drone in real life.

{% include image.html img_url="https://github.com/murdockfpv/murdockfpv.github.io/blob/master/images/list-2021-01-03/3_fat_shark_scout.jpg?raw=true" description="$219 Fat Shark Scout" product_aff_link="https://www.amazon.com/Fat-Shark-Scout-FPV-Goggles/dp/B07V7Y3WX3/ref=sr_1_2?tag=juliusakula-20" %}

{% include image.html img_url="https://github.com/murdockfpv/murdockfpv.github.io/blob/master/images/list-2021-01-03/5_fat_shark_recon.jpg?raw=true" description="$119 Fat Shark Recon" product_aff_link="https://www.amazon.com/Shark-Recon-Goggles-Drone-Racing/dp/B07T27C78F/ref=sr_1_1?tag=juliusakula-20" %}

The Scout and Recon are Fat Shark's budget options compared to their high end goggles. With FPV Goggles, you can connect two pairs to the same video feed when flying and have a spectator watch while you fly, so I plan on getting the cheaper goggles first and upgrading later and keeping my old ones. If I ever were to buy the [$699 DJI Digital FPV goggles](https://www.amazon.com/dp/B07WQQ5KQ6/ref=as_sl_pc_tf_til?tag=juliusakula-20&linkCode=w00&linkId=3d54faceba12fe3c8dbfaa3dc9278635&creativeASIN=B07WQQ5KQ6) or [$739 Fat Shark HDO2(Dominator) FPV Goggles](https://www.amazon.com/dp/B083F815JV/ref=as_sl_pc_tf_til?tag=juliusakula-20&linkCode=w00&linkId=45a4522ca246b3d7c7c35bd8e5bcf680&creativeASIN=B083F815JV) it would be cool to have a spare pair of goggles like the [$220 Fat Shark Scout](
https://www.amazon.com/Fat-Shark-Scout-FPV-Goggles/dp/B07V9TDG5G/ref=sr_1_2?tag=juliusakula-20) or [$130 FatShark Recon](https://www.amazon.com/Shark-Recon-Goggles-Drone-Racing/dp/B07T27C78F/ref=sr_1_1?tag=juliusakula-20) goggles to lend to a friend for a fly-along.

{% include image.html img_url="https://github.com/murdockfpv/murdockfpv.github.io/blob/master/images/list-2021-01-03/12_DJI_digital_fpv.jpg?raw=true" description="$699 DJI Digital FPV goggles" product_aff_link="https://www.amazon.com/dp/B07WQQ5KQ6/ref=as_sl_pc_tf_til?tag=juliusakula-20&linkCode=w00&linkId=3d54faceba12fe3c8dbfaa3dc9278635&creativeASIN=B07WQQ5KQ6" %}

{% include image.html img_url="https://github.com/murdockfpv/murdockfpv.github.io/blob/master/images/list-2021-01-03/16_fat_shark_crossfire.jpg?raw=true" description="$739 Fat Shark HDO2(Dominator) FPV Goggles with Crossfire" product_aff_link="https://www.amazon.com/dp/B083F815JV/ref=as_sl_pc_tf_til?tag=juliusakula-20&linkCode=w00&linkId=45a4522ca246b3d7c7c35bd8e5bcf680&creativeASIN=B083F815JV" %}

**Comment by mallbritten** [comment]
"There are several brands for controllers I just get the impression from Taranis and the silver X9D especially that that is a serious down-to-business drone controller." consider revising this sentence
